package de.bibeltv.mediathek.feature.info

/**
 * Auto-generierte Chronik aller in dieser Entwicklungs-Session getippten Nutzer-Prompts
 * (ohne Screenshots, Task-Benachrichtigungen und Duplikate) mit Zeitpunkt und Antwort-Modell.
 */
data class DevPrompt(val time: String, val model: String, val text: String)

val DEV_PROMPTS: List<DevPrompt> = listOf(
    DevPrompt("27.06.2026, 12:01", "Claude Opus 4.8", "pwd"),
    DevPrompt("27.06.2026, 12:03", "Claude Opus 4.8", "hast du git?"),
    DevPrompt("27.06.2026, 12:16", "Claude Opus 4.8", "ja"),
    DevPrompt("27.06.2026, 12:16", "Claude Opus 4.8", "Hilf mir, SSH-Zugang zu unserem self-hosted GitLab (gitlab.bibel.tv) einzurichten. Arbeite schrittweise und halt an den markierten Stellen an. REGELN: - Den privaten Schlüssel niemals anzeigen, ausgeben, kopieren oder verschieben. Nur den ÖFFENTLICHEN Schlüssel (.pub) darfst du mir zeigen. - Keine Tokens/Passwörter/Schlüssel in Klartext in URLs oder Commit-Messages. SCHRITT 1 – Prüfen, ob schon ein Key da ist: Sieh nach, ob %USERPROFILE%\\.ssh\\id_ed25519 bereits existiert. Falls ja, KEINEN neuen erzeugen, sondern den vorhandenen öffentlichen Schlüssel verwenden und mit Schritt 3 weitermachen. SCHRITT 2 – Key erzeugen (nur falls keiner existiert): Erzeuge ein ed25519-Schlüsselpaar im Standardpfad, ohne Passphrase, nicht interaktiv: ssh-keygen -t ed25519 -C \"brender@bibeltv.de\" -f %USERPROFILE%\\.ssh\\id_ed25519 -N \"\" SCHRITT 3 – Öffentlichen Schlüssel anzeigen und STOPPEN: Gib mir den Inhalt von %USERPROFILE%\\.ssh\\id_ed25519.pub aus (nur diese eine .pub-Zeile). Dann stopp und sag mir wörtlich: \"Trag diese .pub-Zeile in gitlab.bibel.tv unter Benutzereinstellungen → SSH-Keys ein, speichere, und schreib mir dann 'weiter'.\" Erzeuge in der Zwischenzeit nichts weiter und versuche keinen Verbindungsaufbau. SCHRITT 4 – Erst nach meinem \"weiter\": Verbindung testen: ssh -T git@gitlab.bibel.tv Erwartet wird eine Begrüßung mit meinem Benutzernamen (kein Shell-Zugang – das ist normal). Falls der Host-Fingerprint abgefragt wird, erklär mir kurz, was da steht, bevor ich bestätige. Bei Erfolg: melde \"SSH-Anmeldung steht\" und stoppe. Klonen kommt im nächsten Auftrag."),
    DevPrompt("27.06.2026, 12:20", "Claude Opus 4.8", "ist eingetragen"),
    DevPrompt("27.06.2026, 12:22", "Claude Opus 4.8", "weiter"),
    DevPrompt("27.06.2026, 12:23", "Claude Opus 4.8", "passt"),
    DevPrompt("27.06.2026, 12:26", "Claude Opus 4.8", "ok, jetzt lies bitte das md dok anbei in deinem ordner ,bitte fange aber noch nicht an z ucoden. Wir wollen eine moderne, gute Mediatheksapps für Bibel App schreiben mit integrierter Online Bibel. Wir programmieren erst die Mediathek als App von grund auf neu. auf dem videohub kannst du über 20.000 videos abrufen. was brauchst du, um hier eine gute android entwicklungsumgebung zu haben? (bitte noch nichts verändern, wir kären erstmal. Entwicklung oder veränderungen immer vorher fragen, bis ich sage, du sollst mit app entwcklung beginne)"),
    DevPrompt("27.06.2026, 12:55", "Claude Opus 4.8", "moment ,bitte erkläre mit laufziel auch, android studio oberfläche scheint auch spannend zu sein - geht das übrigens auf macos oder windows besser? eine option wäre auch ein neues gerät"),
    DevPrompt("27.06.2026, 13:00", "Claude Opus 4.8", "was kannst du denn selbst installieren für die entwicklungsumgebung, was müsste ich machen?"),
    DevPrompt("27.06.2026, 13:04", "Claude Opus 4.8", "kann ich android studio auch nachträglich installieren?"),
    DevPrompt("27.06.2026, 13:05", "Claude Opus 4.8", "ok, dann bitte jetzt alles installieren, damit du mit entwickeln loslegen kannst"),
    DevPrompt("28.06.2026, 10:19", "Claude Opus 4.8", "prima, dann recherchiere, wie moderne mediatheksapps aussehen und was aus dem videohub kommt. es gibt filme, serien, predigten und vieles. mehr. in deinem verzeichnis hast du die Infos zum videohub mit geheimnis. hast du alles, um recherchieren und die App durchentwickeln zu können? Noch nicht anfangen, nur prüfen, ob du noch was brauchst von mir?"),
    DevPrompt("28.06.2026, 10:26", "Claude Opus 4.8", "du kannst video-hub auch productoin nutzen um zu schauen, was da kommt. aber die erste version von von dir soll gegen videohub beta laufen. Nein, v1 braucht keinen nutzer login. Nimm dir das aktuelle Bibel TV Logo von www.bibeltv.de/presse ,aber ändere seine farben. im neuen CI ist die Form und der Stern wichtig, aber die Farben können sich immer dem Umfeld anpassen. Beta lesezugriff darfst du auch. Es braucht keine Merklisten oder verlauf. Ok, beginne, bis zum fertigen APk - jetzt!"),
    DevPrompt("28.06.2026, 10:27", "Claude Opus 4.8", "ok, beginne jetzt mit dem letzten Prompt"),
    DevPrompt("28.06.2026, 14:34", "Claude Opus 4.8", "arbeite mit modernen und zukunftssicheren und ausbaufähigen architekturen und mitteln kann ich den agenturbrief in markdown lesen?"),
    DevPrompt("28.06.2026, 17:50", "Claude Opus 4.8", "moment, mit stern hatte ich das bibel tv logo gemeint, hattest du es auf www.bibeltv.de/presse gefunden und dir als grafik datei geholt?"),
    DevPrompt("28.06.2026, 21:02", "Claude Opus 4.8", "achtung, beim Logo soll das TV gegen App ersetzt werden, also es heisst bibel.APP nicht, bibel.TV"),
    DevPrompt("28.06.2026, 21:16", "Claude Opus 4.8", "A"),
    DevPrompt("28.06.2026, 21:24", "Claude Opus 4.8", "weiter bauen"),
    DevPrompt("28.06.2026, 22:41", "Claude Opus 4.8", "Commit the working tree changes with a sensible message."),
    DevPrompt("28.06.2026, 22:47", "Claude Opus 4.8", "mache weiter in deinem plan"),
    DevPrompt("28.06.2026, 22:58", "Claude Opus 4.8", "ja, weitermachen und bitte alle erlaubnisse vorher einholen, damit du durcharbeiten kannst"),
    DevPrompt("28.06.2026, 23:33", "Claude Opus 4.8", "und bitte auch suche in die app einbauen, damit inhalte gefunden werden können, die suche soll richtg gut sein"),
    DevPrompt("28.06.2026, 23:53", "Claude Opus 4.8", "ok, bitte checke nochmal alles durch, findest du selbst noch fehler oder bugs, bevor ich suche, die du korrigieren kannst? bitte umfangreiche testbatterie durchführen und dann neue verbesserte version machen, wieder testen usw"),
    DevPrompt("29.06.2026, 00:04", "Claude Opus 4.8", "und bitte auf github pushen"),
    DevPrompt("29.06.2026, 15:06", "Claude Opus 4.8", "wo finde ich das apk der fertigen app?"),
    DevPrompt("29.06.2026, 15:07", "Claude Opus 4.8", "kannst du mir das aplk auch ins ondedrive legen?"),
    DevPrompt("29.06.2026, 15:09", "Claude Opus 4.8", "was ist der unterschied zwischen einem normalen apk und der debug-apk?"),
    DevPrompt("29.06.2026, 16:47", "Claude Opus 4.8", "bitte push die mediatheks app auch in gitlab sofort"),
    DevPrompt("29.06.2026, 17:16", "Claude Opus 4.8", "Bitte gib den Quieries Namen, bitte schreibe immer auf quiery ebene vorher präfix \"bre-testapp-\" - damit der Server weiß, woher es kommt und bitte korrigiere: die Startseite, da laden nur die livestreams oben, der rest lädt nicht"),
    DevPrompt("29.06.2026, 18:22", "Claude Opus 4.8", "schau dir mal alle screenshots an. oben ist sehr viel platz. kann es sein, dass du einen inhaltslosen header und darunter nochmal eine titelleiste hast? Wie auch immer, bitte sorge für eine effiziente seitenausnutzung. bitte links oben noch burger menü einbauen, durch das ich manuell ebenfalls auf die hauptbereiche komme. und im burgermenü sollten auch infos über die app stehen unter \"Info\" und unter \"Einstellungen\" soll ich darkmode / whiteode / wie gerät / oder eigene Zeiten einstellen können. default wäre eigene zeiten, und white von 5.00 Uhr morgens bis 17.00 Uhr, so dass es zum filmeschauen ab 17 Uhr dunekl wird"),
    DevPrompt("29.06.2026, 20:18", "Claude Opus 4.8", "mach noch das Logo so, dass es bündig ist unten"),
    DevPrompt("29.06.2026, 20:23", "Claude Opus 4.8", "und dann bau die Bibelthek rein, mach eine von der usability her durchsachte, super intuitiv zu bedienende Bibelleseoberfläche rein, die mir sowohl einfaches bibellesen ermöglichst als auch jeden nutzer praktisch die mit den versen verbundenen videos zu zeigen"),
    DevPrompt("29.06.2026, 20:24", "Claude Opus 4.8", "bevor du das mit der bibelthek machst, comitte den zwischenstand, pushe ihn auch in beide gits, damit dort alles aktuell ist. wir sind bei der App version 0.8."),
    DevPrompt("29.06.2026, 20:35", "Claude Opus 4.8", "ssh schlüssel ist drin bei doribre"),
    DevPrompt("29.06.2026, 20:37", "Claude Opus 4.8", "Doribre/btv-App-Nachbau-Test-Android Doribre/btv-App-Nachbau-Test-Android Contribute to Doribre/btv-App-Nachbau-Test-Android development by creating an account on GitHub."),
    DevPrompt("29.06.2026, 20:42", "Claude Opus 4.8", "anbindung bibelthek bitte aus deinem md nehmen"),
    DevPrompt("29.06.2026, 20:51", "Claude Opus 4.8", "untersuche mal www.bibeltv.de/bibelthek das ist das gleiche backend, vielleicht hilft die das?"),
    DevPrompt("29.06.2026, 20:57", "Claude Opus 4.8", "schau mal, ob du das aus www.bibeltv.de/bibelthek extrahieren kannst, das geht gegen die gleiche API"),
    DevPrompt("29.06.2026, 21:08", "Claude Opus 4.8", "ja, bitte"),
    DevPrompt("29.06.2026, 21:14", "Claude Opus 4.8", "achtung, du musst dir die bibeln beim anzeigen immer aus dem netz holen, du darfst die nicht lokal speichern"),
    DevPrompt("29.06.2026, 23:23", "Claude Opus 4.8", "moment, es geht darum, die bibelthek in die app einzubauen, die du gebaut hast, keine website zu bauen. aber wenn du keine website gebaut hast, kann das von mir aus im git auch erstmal so bleiben. jetzt vrauchen wir aber noch eine richtig gute Bibelthek in der app"),
    DevPrompt("30.06.2026, 01:06", "Claude Opus 4.8", "was wäre die alternative zum html parsing? ich hätte gerne eine stabile native app"),
    DevPrompt("30.06.2026, 01:12", "Claude Opus 4.8", "@\"C:\\Users\\Kai_Imbredienst\\OneDrive - Bibel TV Stiftung gemeinnützige GmbH\\Desktop\\28009-signierte App.apk\" hilft dir die bibel tv app?"),
    DevPrompt("30.06.2026, 01:18", "Claude Opus 4.8", "und hol dir auch gleich die infos aus der app, wie das mit dem login geht und wie du drm-videos anzeigen kannst"),
    DevPrompt("30.06.2026, 01:21", "Claude Opus 4.8", "prima, dann bau es in die app"),
    DevPrompt("30.06.2026, 06:31", "Claude Opus 4.8", "2"),
    DevPrompt("30.06.2026, 06:34", "Claude Opus 4.8", "bitte aktuellen stand in github und gutlab pushen"),
    DevPrompt("30.06.2026, 06:36", "Claude Opus 4.8", "bitte die bibeltheks spec in docs ordner aufnhemen"),
    DevPrompt("30.06.2026, 06:38", "Claude Opus 4.8", "wo finde ich die aktuellste ganze apk zum testen?"),
    DevPrompt("30.06.2026, 06:46", "Claude Opus 4.8", "kannst du mir den link zum onedirve geben anklickbar"),
    DevPrompt("30.06.2026, 07:09", "Claude Opus 4.8", "link zum onedrive geht nicht, kannst du das im explorer anzeigen?"),
    DevPrompt("30.06.2026, 07:13", "Claude Opus 4.8", "danke, wir können die version 0.9 nennen, bitte im explorer anzeigen"),
    DevPrompt("01.07.2026, 16:14", "Claude Opus 4.8", "prima, dann bitte neues APk machen, ich würde gerne auf der Startseite kurzen kleinen Teasertext für Hero integriert unter dem livestream \"Bibel TV\" ein link zum epg klein rechts unten in den Videokarten auf der Startseite und bei entdecken die LAufzeit, also zu Beipsiel 28:00 dass die suche auch eine Volltextsuche in der Bibel integriert und mit den anderen Suchergebnisse ausliefert. Da möchte ich klicken und die entsprechende Stelle in der Bibelthek öffnen können: dann möchte ich im Bibeltext selbst erkennen (ein und ausschaltbar), zu welchem vers es wie viele videosgibt"),
    DevPrompt("01.07.2026, 16:34", "Claude Opus 4.8", "das wäre dann version 0.99"),
    DevPrompt("01.07.2026, 17:44", "Claude Opus 4.8", "teste mal, ob ich über suche sowohl bibel volltexten als auch mediathek suchen kann über die eine suchfunktion"),
    DevPrompt("01.07.2026, 17:45", "Claude Opus 4.8", "und zeig mal, wie die neue statrseite gerendert aussieht"),
    DevPrompt("01.07.2026, 17:48", "Claude Opus 4.8", "ich hätte gerne noch den EPG Text kurz für 2 Zeilen auf dem Header blld - bitte so eng kompakt, dass es dennoch aufgerumt aussieht und zeig dann ochmal die neue statrseite"),
    DevPrompt("01.07.2026, 19:20", "Claude Opus 4.8", "bitte die Absätze mit wenig zeilenddurchschuss, so dass der abstand zwischen den absätzen größer ist als der innerhalb auf dem header"),
    DevPrompt("01.07.2026, 19:25", "Claude Opus 4.8", "super, aber bitte Titel auf dem Header und Kurz EPG und Button so Anordnen, dass alles etwas unterhalb der Mitte zu ende ist und nicht höher reicht, mach dir gute gedanken und überprüfe es mehrmals"),
    DevPrompt("01.07.2026, 19:42", "Claude Opus 4.8", "auchtung, alles unterhalb der header mitte auf dem headerbild, damit man die augen und motive, die meisten in der mitte oder leicht drübder sind, gut sehen kann, bitte machen, bedenken und gut überprüfen"),
    DevPrompt("01.07.2026, 22:39", "Claude Opus 4.8", "ja, zeig mal"),
    DevPrompt("01.07.2026, 22:40", "Claude Opus 4.8", "und zeig auch mal, wie die suchergebnisseite aussieht"),
    DevPrompt("01.07.2026, 22:42", "Claude Opus 4.8", "ok, das ist mir gerade etwas zu sehr reingezoomt undzu groß. kannst du ein klein bisschen wieder weniger hoch machen, so dass es dennoch unter der Mittellinie bleibt?"),
    DevPrompt("01.07.2026, 22:49", "Claude Opus 4.8", "ok, mache es nur minimalst flacher. Und hast du einen Weg bei der suche, die Bibel und die Mediathek nach Relevanz in sich zusammen zu sortieren? also nicht einen Teil Bibe lund einenn teil Mediatehk, sondern aus beidem gemischt die am besten passenden Treffer?7"),
    DevPrompt("01.07.2026, 23:38", "Claude Opus 4.8", "ja, aber wenn eine Bibelstelle konkret eingegeben wird wie mt 8 oder matthäus 8 soll er gleich das entsprechende kapitel in der bibelthek öffnen, gar keine suchergebnisse anzeigen"),
    DevPrompt("01.07.2026, 23:54", "Claude Opus 4.8", "er soll auch loccumer abkürzungen verstehen und bitte noch eine Info rein, welche Version und Liste aller Prompts, die ich hier bisher getippt habe mit Datum und Uhrzeit und deinem Modell, mit dem du geantwortet hast"),
)
